import { ILuggage, LuggageType, Location } from '@hems/interfaces';

export const luggages: ILuggage[] = [
  {
    luggageId: '063a6ba5-2114-47d9-87e7-612ba8ef05c6',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '23',
    name: 'Harri Jollye',
    arrivalTime: new Date('6/15/2022'),
    bags: 'Major Banks',
    tagNr: '26549',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PH',
    bbLr: 'IQ',
    bbOut: 'ID',
  },
  {
    luggageId: 'e1f64023-8b0e-4b16-a400-61f17463d59b',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '1',
    name: 'Nina Paynton',
    arrivalTime: new Date('12/10/2021'),
    bags: 'Specialty Foods',
    tagNr: '33',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'TD',
    bbLr: 'CN',
    bbOut: 'ID',
  },
  {
    luggageId: '8c20b435-f5fa-42e4-b4b6-e4c10157e464',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '5',
    name: 'Reggie Wallis',
    arrivalTime: new Date('11/11/2022'),
    bags: 'Oil & Gas Production',
    tagNr: '27841',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PH',
    bbLr: 'EC',
    bbOut: 'DO',
  },
  {
    luggageId: '897fb456-8370-4cc8-b6ec-536d398aec26',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '09',
    name: 'Juieta Gippes',
    arrivalTime: new Date('2/21/2022'),
    bags: 'Property-Casualty Insurers',
    tagNr: '67',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'PT',
    bbOut: 'CN',
  },
  {
    luggageId: 'b39a660e-f2cd-4382-9708-8e1f1e904251',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '15',
    name: 'Roscoe Ceaplen',
    arrivalTime: new Date('11/1/2022'),
    bags: 'Savings Institutions',
    tagNr: '50',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'GR',
    bbLr: 'RU',
    bbOut: 'NG',
  },
  {
    luggageId: 'd98d3d74-e232-4389-9242-2f54957f890b',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '21437',
    name: 'Tiphany Wharfe',
    arrivalTime: new Date('5/28/2022'),
    bags: 'Property-Casualty Insurers',
    tagNr: '7210',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'RU',
    bbLr: 'AZ',
    bbOut: 'PT',
  },
  {
    luggageId: 'f187f086-3981-4158-a4ab-0792a196d433',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '686',
    name: 'Fraze Oxenden',
    arrivalTime: new Date('10/19/2022'),
    bags: 'Building Products',
    tagNr: '4',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'DO',
    bbOut: 'PL',
  },
  {
    luggageId: '207d7399-909d-4b42-9120-13ef04b0fdd4',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '9',
    name: 'Warde Gisbye',
    arrivalTime: new Date('8/22/2022'),
    bags: 'Business Services',
    tagNr: '173',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'UA',
    bbOut: 'BR',
  },
  {
    luggageId: '90e07c92-5e82-494d-a4aa-bf865a110640',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '1',
    name: 'Cathlene McLaverty',
    arrivalTime: new Date('7/9/2022'),
    bags: 'Restaurants',
    tagNr: '470',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'BR',
    bbLr: 'JO',
    bbOut: 'ID',
  },
  {
    luggageId: 'ecc683af-992d-4949-8992-8f5240e764a0',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '8',
    name: 'Elaine Veltman',
    arrivalTime: new Date('7/3/2022'),
    bags: 'Major Pharmaceuticals',
    tagNr: '42',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'BR',
    bbLr: 'ZA',
    bbOut: 'CN',
  },
  {
    luggageId: '0ab9124c-912e-405f-8700-931e648f16f9',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '4241',
    name: 'Tad Dagnall',
    arrivalTime: new Date('7/4/2022'),
    bags: 'n/a',
    tagNr: '17',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'PH',
    bbOut: 'PH',
  },
  {
    luggageId: 'f2e13e1d-7279-460e-8485-f6d1cf94a598',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '8',
    name: 'Howard Dallan',
    arrivalTime: new Date('7/17/2022'),
    bags: 'Beverages (Production/Distribution)',
    tagNr: '77',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PE',
    bbLr: 'CN',
    bbOut: 'CN',
  },
  {
    luggageId: '83891044-90ce-47e7-ad93-82d6190b6de3',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '80',
    name: 'Mellisa Stonehewer',
    arrivalTime: new Date('2/24/2022'),
    bags: 'Major Pharmaceuticals',
    tagNr: '4814',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'GR',
    bbLr: 'CN',
    bbOut: 'CN',
  },
  {
    luggageId: '40ffc9e3-11b2-4903-b2d1-cdf92129484b',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '8383',
    name: 'Emerson Longhorne',
    arrivalTime: new Date('1/13/2022'),
    bags: 'Major Banks',
    tagNr: '996',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'FR',
    bbOut: 'CN',
  },
  {
    luggageId: '63b789bf-c9d7-41f4-8a10-eb997f0d00d5',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '9',
    name: 'Stacy Taunton.',
    arrivalTime: new Date('11/11/2022'),
    bags: 'Beverages (Production/Distribution)',
    tagNr: '422',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'RU',
    bbLr: 'SE',
    bbOut: 'RU',
  },
  {
    luggageId: '44bca426-50bb-4c09-9048-51dd3117a430',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '085',
    name: 'Edithe Fursse',
    arrivalTime: new Date('9/12/2022'),
    bags: 'n/a',
    tagNr: '9897',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'RU',
    bbLr: 'ID',
    bbOut: 'PE',
  },
  {
    luggageId: 'ff6d7537-95b8-4dba-b77e-3794282481af',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '89',
    name: 'Renelle Zamorano',
    arrivalTime: new Date('10/23/2022'),
    bags: 'Major Pharmaceuticals',
    tagNr: '11688',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PH',
    bbLr: 'BR',
    bbOut: 'RU',
  },
  {
    luggageId: '07493116-cd4b-441e-bae5-cdbe65e2e01c',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '0',
    name: 'Hayden Skacel',
    arrivalTime: new Date('6/18/2022'),
    bags: 'Office Equipment/Supplies/Services',
    tagNr: '9',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'EC',
    bbLr: 'BR',
    bbOut: 'RU',
  },
  {
    luggageId: 'a9747941-6f94-48a2-a8e1-8acc779e0a15',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '4',
    name: 'Dominick Bafford',
    arrivalTime: new Date('1/5/2022'),
    bags: 'Real Estate Investment Trusts',
    tagNr: '129',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CA',
    bbLr: 'PT',
    bbOut: 'PH',
  },
  {
    luggageId: 'a259d018-3743-4f84-b513-66cf886db685',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '494',
    name: 'Brod Shovlin',
    arrivalTime: new Date('2/20/2022'),
    bags: 'Oil & Gas Production',
    tagNr: '950',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'FR',
    bbLr: 'KR',
    bbOut: 'MN',
  },
  {
    luggageId: 'ad8305e3-ab56-4c49-ae6e-734e656dde94',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '4',
    name: 'Cash Jiroutka',
    arrivalTime: new Date('6/24/2022'),
    bags: 'Real Estate Investment Trusts',
    tagNr: '051',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'AL',
    bbLr: 'PE',
    bbOut: 'MX',
  },
  {
    luggageId: 'bdf51860-5489-4e76-95b1-5192627432bc',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '88',
    name: 'Kelli Hanfrey',
    arrivalTime: new Date('8/6/2022'),
    bags: 'Industrial Machinery/Components',
    tagNr: '8513',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'SE',
    bbLr: 'PT',
    bbOut: 'NZ',
  },
  {
    luggageId: 'f05be639-fb3f-4219-a50c-346d52f872d9',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '817',
    name: 'Misti Trippack',
    arrivalTime: new Date('7/13/2022'),
    bags: 'Property-Casualty Insurers',
    tagNr: '6820',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'JP',
    bbOut: 'BR',
  },
  {
    luggageId: 'be6dbc48-65a3-4e92-b37e-ec6ff21517cc',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '6',
    name: 'Colver Gobolos',
    arrivalTime: new Date('11/30/2021'),
    bags: 'Automotive Aftermarket',
    tagNr: '8',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'NL',
    bbLr: 'GR',
    bbOut: 'SE',
  },
  {
    luggageId: '34051daa-698f-4d1f-b6b9-09c82d7c6d98',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '8',
    name: 'Brant Fernando',
    arrivalTime: new Date('11/2/2022'),
    bags: 'Real Estate Investment Trusts',
    tagNr: '1',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'MN',
    bbOut: 'IE',
  },
  {
    luggageId: 'f4786596-7fb2-4ddc-9ea8-e76e2f0e5663',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '4',
    name: 'Ode Perford',
    arrivalTime: new Date('3/1/2022'),
    bags: 'Diversified Commercial Services',
    tagNr: '53',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'TM',
    bbLr: 'HR',
    bbOut: 'ID',
  },
  {
    luggageId: '5e8650df-8f83-4fd8-92e0-13f02d5c8dd8',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '62',
    name: 'Tedi Dibson',
    arrivalTime: new Date('2/9/2022'),
    bags: 'n/a',
    tagNr: '119',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'AE',
    bbLr: 'PH',
    bbOut: 'RU',
  },
  {
    luggageId: 'ed2c70e4-181b-427e-a8b4-0de6db2045ee',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '416',
    name: 'Billie Hailes',
    arrivalTime: new Date('6/28/2022'),
    bags: 'Oilfield Services/Equipment',
    tagNr: '69',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'RU',
    bbLr: 'PH',
    bbOut: 'ID',
  },
  {
    luggageId: '39570bb2-91fa-48da-96c2-6ee07d27a794',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '7',
    name: 'Margit Darycott',
    arrivalTime: new Date('6/20/2022'),
    bags: 'Biotechnology: Biological Products (No Diagnostic Substances)',
    tagNr: '6152',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'RU',
    bbLr: 'CN',
    bbOut: 'RU',
  },
  {
    luggageId: '241434ab-0984-4c46-a6fd-1e052966042a',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '6052',
    name: 'Cletus Patridge',
    arrivalTime: new Date('11/17/2022'),
    bags: 'Forest Products',
    tagNr: '1493',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'TG',
    bbLr: 'GR',
    bbOut: 'ID',
  },
  {
    luggageId: '04fb17b1-1ecf-478a-a298-f935df710c15',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '025',
    name: 'Morgan Scutter',
    arrivalTime: new Date('1/6/2022'),
    bags: 'n/a',
    tagNr: '9',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'BR',
    bbLr: 'PT',
    bbOut: 'PL',
  },
  {
    luggageId: '1a448e91-dccf-4a00-b831-7568843518e5',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '51',
    name: 'Aeriell Massot',
    arrivalTime: new Date('7/14/2022'),
    bags: 'Semiconductors',
    tagNr: '060',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'CI',
    bbOut: 'TH',
  },
  {
    luggageId: 'c1ece594-8336-4b7a-87dc-0d532e70242b',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '78436',
    name: 'Alejandrina Brand',
    arrivalTime: new Date('12/18/2021'),
    bags: 'n/a',
    tagNr: '73268',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PH',
    bbLr: 'UG',
    bbOut: 'UA',
  },
  {
    luggageId: 'c56057bc-bf5b-41cb-b6fa-0e1dafda96f7',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '12',
    name: 'Dorry Tretwell',
    arrivalTime: new Date('11/6/2022'),
    bags: 'Computer Software: Prepackaged Software',
    tagNr: '2949',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'RU',
    bbOut: 'PT',
  },
  {
    luggageId: '63ca091f-2391-4ffa-a4c8-d01869ce766a',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '6108',
    name: 'Codie Dulen',
    arrivalTime: new Date('6/2/2022'),
    bags: 'n/a',
    tagNr: '2354',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'MX',
    bbLr: 'BA',
    bbOut: 'BW',
  },
  {
    luggageId: '791e6ce0-9711-4810-9ca4-8c64e9264666',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '88',
    name: 'Sibyl Ausello',
    arrivalTime: new Date('5/27/2022'),
    bags: 'n/a',
    tagNr: '973',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'JP',
    bbLr: 'CN',
    bbOut: 'CN',
  },
  {
    luggageId: '77300d32-083a-4483-a551-3b67d48b8d51',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '3950',
    name: 'Jenilee Clears',
    arrivalTime: new Date('10/17/2022'),
    bags: 'n/a',
    tagNr: '7',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'RU',
    bbLr: 'CO',
    bbOut: 'SI',
  },
  {
    luggageId: '848c0fb5-36b7-477f-8a45-880d1bfa2efd',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '675',
    name: 'Zach Lias',
    arrivalTime: new Date('9/12/2022'),
    bags: 'Environmental Services',
    tagNr: '007',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CU',
    bbLr: 'PL',
    bbOut: 'PH',
  },
  {
    luggageId: '3f6f8231-67b8-4337-b6d1-070345a29b69',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '45',
    name: 'Goldy Schowenburg',
    arrivalTime: new Date('12/19/2021'),
    bags: 'Department/Specialty Retail Stores',
    tagNr: '2085',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CU',
    bbLr: 'FR',
    bbOut: 'BG',
  },
  {
    luggageId: '6f49c7de-94a7-4643-a016-34851b16a007',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '85',
    name: 'Leif Shepherdson',
    arrivalTime: new Date('1/11/2022'),
    bags: 'Major Banks',
    tagNr: '5856',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'ES',
    bbOut: 'CD',
  },
  {
    luggageId: '9fe036fc-4cdc-4c11-aee7-b239ed4b18f7',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '8',
    name: 'Dougy Mushrow',
    arrivalTime: new Date('10/6/2022'),
    bags: 'Other Consumer Services',
    tagNr: '3',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'AM',
    bbLr: 'PH',
    bbOut: 'CI',
  },
  {
    luggageId: 'f76c8084-21f2-4287-8633-e1f24b3d3bd8',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '7',
    name: 'Ingemar Brakespear',
    arrivalTime: new Date('9/10/2022'),
    bags: 'Industrial Machinery/Components',
    tagNr: '0258',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'FR',
    bbLr: 'CN',
    bbOut: 'TH',
  },
  {
    luggageId: '678035d6-c065-4195-bdb5-c029281b58a4',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '93913',
    name: 'Maressa Tabourier',
    arrivalTime: new Date('4/23/2022'),
    bags: 'Computer Software: Prepackaged Software',
    tagNr: '567',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'HR',
    bbOut: 'CN',
  },
  {
    luggageId: '5c7fbf25-4da7-438c-aa66-9cc1b73ededb',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '4',
    name: 'Chiquita Challis',
    arrivalTime: new Date('8/12/2022'),
    bags: 'Medical/Nursing Services',
    tagNr: '24',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'BR',
    bbLr: 'CN',
    bbOut: 'PL',
  },
  {
    luggageId: '332faed5-174a-4fbb-b79d-31d8eeb93783',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '327',
    name: 'Ailee Tolchar',
    arrivalTime: new Date('6/28/2022'),
    bags: 'n/a',
    tagNr: '8819',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PK',
    bbLr: 'CN',
    bbOut: 'NO',
  },
  {
    luggageId: '15cb7e4d-666a-4856-b9c0-5e2a3597fa93',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '07',
    name: 'Annalee Ingleby',
    arrivalTime: new Date('4/16/2022'),
    bags: 'Other Consumer Services',
    tagNr: '0',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PL',
    bbLr: 'SE',
    bbOut: 'CN',
  },
  {
    luggageId: 'f7d6b714-6bfe-4c6b-9144-d3f1aa74b40e',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '45511',
    name: 'Woodman Files',
    arrivalTime: new Date('10/9/2022'),
    bags: 'Environmental Services',
    tagNr: '610',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'AR',
    bbLr: 'RU',
    bbOut: 'KE',
  },
  {
    luggageId: '43327c9f-80a5-4e0a-ada9-8625e23a65f5',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '91',
    name: 'Evey Lampel',
    arrivalTime: new Date('12/25/2021'),
    bags: 'EDP Services',
    tagNr: '4173',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'RU',
    bbOut: 'CN',
  },
  {
    luggageId: 'f2c52f74-d40f-485c-a122-31489aa6266f',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '15351',
    name: 'Elberta Ogley',
    arrivalTime: new Date('11/2/2022'),
    bags: 'Property-Casualty Insurers',
    tagNr: '57',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'CN',
    bbOut: 'TH',
  },
  {
    luggageId: '2511af91-872d-4d16-af49-341257de675f',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '53400',
    name: 'Desi Flanders',
    arrivalTime: new Date('4/23/2022'),
    bags: 'n/a',
    tagNr: '259',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'TH',
    bbOut: 'CN',
  },
  {
    luggageId: 'c0d71d24-24ce-4a18-a98d-41c54ace4d9e',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '308',
    name: 'Norbert Whitely',
    arrivalTime: new Date('2/3/2022'),
    bags: 'Real Estate Investment Trusts',
    tagNr: '78',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PL',
    bbLr: 'BR',
    bbOut: 'ML',
  },
  {
    luggageId: 'a0f7257d-b66e-4058-9375-325258fba27c',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '43',
    name: 'Michaella Durbridge',
    arrivalTime: new Date('6/2/2022'),
    bags: 'Medical Specialities',
    tagNr: '5694',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'SE',
    bbLr: 'GR',
    bbOut: 'CZ',
  },
  {
    luggageId: '33d68ab8-6346-4ed7-bd36-4c785c0a6381',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '4780',
    name: 'Celestine Kleinhandler',
    arrivalTime: new Date('11/10/2022'),
    bags: 'Major Banks',
    tagNr: '15012',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'SE',
    bbOut: 'AL',
  },
  {
    luggageId: '9b5b0664-6031-4ba5-9fbb-3d01db4e6967',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '5889',
    name: 'Caleb Hargate',
    arrivalTime: new Date('2/22/2022'),
    bags: 'Electrical Products',
    tagNr: '414',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'RU',
    bbOut: 'ID',
  },
  {
    luggageId: 'bdb0a53d-8e3e-41bc-a81b-ebf3ba9b76db',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '6225',
    name: 'Ashely Thoma',
    arrivalTime: new Date('5/1/2022'),
    bags: 'Savings Institutions',
    tagNr: '0863',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PH',
    bbLr: 'HR',
    bbOut: 'PL',
  },
  {
    luggageId: 'a50caf12-8260-49d7-885d-d1de78c3fc7f',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '6',
    name: 'Yorker Pacey',
    arrivalTime: new Date('3/4/2022'),
    bags: 'Radio And Television Broadcasting And Communications Equipment',
    tagNr: '1',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'RU',
    bbLr: 'RU',
    bbOut: 'VE',
  },
  {
    luggageId: '02de5b51-65ac-4a93-bcdb-ceeab78530ec',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '5',
    name: 'Jobyna Nealy',
    arrivalTime: new Date('9/6/2022'),
    bags: 'n/a',
    tagNr: '77723',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PL',
    bbLr: 'CN',
    bbOut: 'NI',
  },
  {
    luggageId: 'c9fa8879-c95f-4767-aebd-20061a0d110c',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '65723',
    name: 'Luke Marin',
    arrivalTime: new Date('3/2/2022'),
    bags: 'Major Pharmaceuticals',
    tagNr: '2353',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'UA',
    bbLr: 'MG',
    bbOut: 'JP',
  },
  {
    luggageId: '0dcae95e-f51b-482c-b680-512c7bfd8def',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '742',
    name: 'Janifer Brereton',
    arrivalTime: new Date('2/2/2022'),
    bags: 'Marine Transportation',
    tagNr: '3705',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'PT',
    bbOut: 'TH',
  },
  {
    luggageId: '8c281daf-c400-4ffc-94f2-1ff296eb828a',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '2488',
    name: 'Dorella Kitcherside',
    arrivalTime: new Date('8/4/2022'),
    bags: 'Trucking Freight/Courier Services',
    tagNr: '1614',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'NL',
    bbOut: 'PL',
  },
  {
    luggageId: '255b44d9-22f5-43f7-b93c-492e29085b4c',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '8',
    name: 'Iggy Castaner',
    arrivalTime: new Date('12/25/2021'),
    bags: 'n/a',
    tagNr: '29353',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'RU',
    bbLr: 'US',
    bbOut: 'ID',
  },
  {
    luggageId: '03165ecf-3591-4a2e-acb5-e04a4f42553d',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '7105',
    name: 'Aidan Labba',
    arrivalTime: new Date('4/28/2022'),
    bags: 'Major Banks',
    tagNr: '015',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'HR',
    bbLr: 'US',
    bbOut: 'ID',
  },
  {
    luggageId: '61bac914-a4f3-4bc8-a687-e545e12712ac',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '19',
    name: 'Sam Chifney',
    arrivalTime: new Date('11/20/2021'),
    bags: 'Major Banks',
    tagNr: '7556',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'MK',
    bbLr: 'NG',
    bbOut: 'ID',
  },
  {
    luggageId: '3c9a8270-cd69-4a8e-bc2a-94e5e9c4e76f',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '7',
    name: 'Tan Feria',
    arrivalTime: new Date('4/25/2022'),
    bags: 'Medical/Dental Instruments',
    tagNr: '42703',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'UA',
    bbLr: 'RU',
    bbOut: 'TH',
  },
  {
    luggageId: '54a4f2e8-e5fc-4aa4-96d5-a45f91bcd9e2',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '09260',
    name: 'Catharina Tongue',
    arrivalTime: new Date('10/14/2022'),
    bags: 'n/a',
    tagNr: '4805',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'SE',
    bbLr: 'ID',
    bbOut: 'NG',
  },
  {
    luggageId: '743c5781-6f29-411a-9bcd-3b60d15ff1ba',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '1',
    name: 'Tomi Aldcorne',
    arrivalTime: new Date('10/29/2022'),
    bags: 'Medical/Dental Instruments',
    tagNr: '4461',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'FR',
    bbLr: 'PT',
    bbOut: 'JP',
  },
  {
    luggageId: '974945e1-f744-4f62-8a56-aeef4eac9abc',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '976',
    name: 'Nada Weare',
    arrivalTime: new Date('5/15/2022'),
    bags: 'Computer Manufacturing',
    tagNr: '024',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CL',
    bbLr: 'US',
    bbOut: 'PH',
  },
  {
    luggageId: '37d432ea-6bb3-44b0-93b8-057132e09ff1',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '51',
    name: 'Magnum Lounds',
    arrivalTime: new Date('10/21/2022'),
    bags: 'Investment Managers',
    tagNr: '86',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'RS',
    bbLr: 'LA',
    bbOut: 'CN',
  },
  {
    luggageId: 'f5053a97-1cb0-4c55-b49a-aae93469e652',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '09',
    name: 'Clarinda Tadman',
    arrivalTime: new Date('3/26/2022'),
    bags: 'Marine Transportation',
    tagNr: '2',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'RU',
    bbLr: 'RU',
    bbOut: 'CN',
  },
  {
    luggageId: '29e1e281-1d08-44d9-bfb1-1a0ab93222b7',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '10',
    name: 'Livia Berick',
    arrivalTime: new Date('12/12/2021'),
    bags: 'Oil & Gas Production',
    tagNr: '67',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'BA',
    bbOut: 'ID',
  },
  {
    luggageId: '189eecb8-e69c-49c9-9c64-1ef0e9591946',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '3796',
    name: 'Una Niece',
    arrivalTime: new Date('7/24/2022'),
    bags: 'Business Services',
    tagNr: '044',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'MY',
    bbLr: 'ID',
    bbOut: 'CN',
  },
  {
    luggageId: '5b188a47-50a2-4d60-b644-443c8fe36245',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '647',
    name: 'Georg Darko',
    arrivalTime: new Date('2/2/2022'),
    bags: 'Major Banks',
    tagNr: '5',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'CZ',
    bbOut: 'ID',
  },
  {
    luggageId: 'eed57e04-a796-48be-8ccd-1020b79b4f9c',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '8879',
    name: 'Bear Bretelle',
    arrivalTime: new Date('7/14/2022'),
    bags: 'EDP Services',
    tagNr: '729',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CZ',
    bbLr: 'CN',
    bbOut: 'CO',
  },
  {
    luggageId: '7e7ef9cd-28eb-4b55-8ed1-0a98cb6e7123',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '85379',
    name: 'Hayyim Van Eeden',
    arrivalTime: new Date('3/25/2022'),
    bags: 'Construction/Ag Equipment/Trucks',
    tagNr: '57',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'GT',
    bbLr: 'CR',
    bbOut: 'DE',
  },
  {
    luggageId: 'acfddd76-6b43-44f5-9c68-4b3bd0a39b4d',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '7983',
    name: 'Dru Rainsbury',
    arrivalTime: new Date('7/3/2022'),
    bags: 'Major Banks',
    tagNr: '0354',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'AL',
    bbLr: 'MX',
    bbOut: 'CN',
  },
  {
    luggageId: 'a7be9f65-4966-4bed-abf2-53e624ff5553',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '523',
    name: 'Base Echallier',
    arrivalTime: new Date('6/12/2022'),
    bags: 'Oil & Gas Production',
    tagNr: '8639',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PH',
    bbLr: 'PT',
    bbOut: 'NG',
  },
  {
    luggageId: '1f655527-00d7-4972-ab20-5da6d55ae426',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '735',
    name: 'Darby Spolton',
    arrivalTime: new Date('1/12/2022'),
    bags: 'Major Banks',
    tagNr: '5215',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'CN',
    bbOut: 'PL',
  },
  {
    luggageId: 'b878c8fb-f23a-4b81-9f02-a714fceef20b',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '40593',
    name: 'Loutitia Puckey',
    arrivalTime: new Date('9/7/2022'),
    bags: 'Real Estate Investment Trusts',
    tagNr: '4899',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ZA',
    bbLr: 'PL',
    bbOut: 'PH',
  },
  {
    luggageId: '9266b3c7-0ae0-4523-b713-34e54ae50356',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '1',
    name: 'Saul Fairham',
    arrivalTime: new Date('1/31/2022'),
    bags: 'Diversified Commercial Services',
    tagNr: '744',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'FM',
    bbOut: 'JO',
  },
  {
    luggageId: '74d4d87c-22f2-4840-a3c3-bf4c184dfad0',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '683',
    name: 'Feliza Riseborough',
    arrivalTime: new Date('7/23/2022'),
    bags: 'Property-Casualty Insurers',
    tagNr: '59',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PH',
    bbLr: 'CN',
    bbOut: 'RU',
  },
  {
    luggageId: '1920b743-61c1-46bb-aa36-c375a7431890',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '00325',
    name: 'Elspeth Mattessen',
    arrivalTime: new Date('3/17/2022'),
    bags: 'Medical/Dental Instruments',
    tagNr: '7',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'NZ',
    bbLr: 'GR',
    bbOut: 'RU',
  },
  {
    luggageId: 'a761a9e4-47c9-453f-b40c-377db99eea93',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '94609',
    name: 'Goraud Aleksandrikin',
    arrivalTime: new Date('6/17/2022'),
    bags: 'Major Pharmaceuticals',
    tagNr: '2603',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'BR',
    bbLr: 'CN',
    bbOut: 'AL',
  },
  {
    luggageId: '41bcce5d-f351-48d8-aa20-46c8fdad2897',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '190',
    name: "Lidia O'Lahy",
    arrivalTime: new Date('7/17/2022'),
    bags: 'n/a',
    tagNr: '7',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'US',
    bbLr: 'FR',
    bbOut: 'CN',
  },
  {
    luggageId: 'd97bca93-c780-4d58-b95b-1508590f1fe9',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '97',
    name: 'Belle Eagleston',
    arrivalTime: new Date('7/17/2022'),
    bags: 'n/a',
    tagNr: '97',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'HN',
    bbLr: 'BT',
    bbOut: 'CN',
  },
  {
    luggageId: 'a9a97376-7978-48ae-a594-f9b91044d606',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '828',
    name: 'Merlina Foottit',
    arrivalTime: new Date('8/17/2022'),
    bags: 'EDP Services',
    tagNr: '539',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'CO',
    bbOut: 'AR',
  },
  {
    luggageId: '9f907d39-63b5-4384-b43a-94cd8341df1a',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '51',
    name: 'Josephina Chaperling',
    arrivalTime: new Date('11/17/2022'),
    bags: 'Major Banks',
    tagNr: '09640',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'CN',
    bbLr: 'CL',
    bbOut: 'TH',
  },
  {
    luggageId: '3ee7eef6-951f-45bc-8f46-2318cd93dfc9',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '08309',
    name: 'Jock Giovannini',
    arrivalTime: new Date('10/10/2022'),
    bags: 'Major Banks',
    tagNr: '214',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PH',
    bbLr: 'PT',
    bbOut: 'CN',
  },
  {
    luggageId: '6cf73d0f-9c3b-49c8-9d7f-7c6ad0968d15',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '7859',
    name: 'Avrit Cherrison',
    arrivalTime: new Date('1/21/2022'),
    bags: 'Oil & Gas Production',
    tagNr: '6912',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'NP',
    bbLr: 'AL',
    bbOut: 'BR',
  },
  {
    luggageId: '8c7ac359-86da-4730-81f3-e227d5041fef',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '272',
    name: 'Kerianne Askwith',
    arrivalTime: new Date('10/16/2022'),
    bags: 'Aerospace',
    tagNr: '2367',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'KM',
    bbLr: 'FR',
    bbOut: 'GR',
  },
  {
    luggageId: 'd84fc6f6-143e-4e64-bfc2-3293ae238fe4',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '80',
    name: 'Den Snel',
    arrivalTime: new Date('10/18/2022'),
    bags: 'n/a',
    tagNr: '1716',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'AL',
    bbLr: 'PL',
    bbOut: 'PT',
  },
  {
    luggageId: 'b1ddcfb1-58e6-4027-88b8-d8adc8b8b92a',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '5378',
    name: 'Sheryl Monte',
    arrivalTime: new Date('7/22/2022'),
    bags: 'n/a',
    tagNr: '624',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'IL',
    bbLr: 'NA',
    bbOut: 'ID',
  },
  {
    luggageId: '4e74a9c9-8eb4-4e22-b749-c83a3f2bd8ee',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '33',
    name: 'Tomaso Aspray',
    arrivalTime: new Date('3/14/2022'),
    bags: 'Business Services',
    tagNr: '7777',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PT',
    bbLr: 'BY',
    bbOut: 'PL',
  },
  {
    luggageId: 'c56d987d-db84-4da7-a6cb-5050d3b2c8a6',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '58',
    name: 'Terrie Bitcheno',
    arrivalTime: new Date('5/25/2022'),
    bags: 'EDP Services',
    tagNr: '629',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'PH',
    bbLr: 'US',
    bbOut: 'CN',
  },
  {
    luggageId: 'fe3126c5-3618-4a76-8a91-55daef6f0e3e',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '409',
    name: 'Christoforo Lenchenko',
    arrivalTime: new Date('11/3/2022'),
    bags: 'Major Banks',
    tagNr: '2074',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'GR',
    bbLr: 'NG',
    bbOut: 'UG',
  },
  {
    luggageId: '1164f92a-c812-4303-af79-95023f2d5fd5',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '6606',
    name: 'Demetri Ricardin',
    arrivalTime: new Date('1/5/2022'),
    bags: 'n/a',
    tagNr: '304',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'NO',
    bbOut: 'RU',
  },
  {
    luggageId: '9e36b5c0-03bc-4cf0-9688-12ba5ef5a72f',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '830',
    name: 'Vaclav Ladel',
    arrivalTime: new Date('1/18/2022'),
    bags: 'Oil & Gas Production',
    tagNr: '18666',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'FI',
    bbOut: 'FR',
  },
  {
    luggageId: '0f7ce862-3bc2-45cc-80aa-ee215d076e07',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '01',
    name: 'Prinz Blasing',
    arrivalTime: new Date('3/5/2022'),
    bags: 'Professional Services',
    tagNr: '9',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'JP',
    bbLr: 'TG',
    bbOut: 'TH',
  },
  {
    luggageId: 'f0c36ee0-650e-45a9-88b2-8e406a124406',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '2878',
    name: 'Loria Immings',
    arrivalTime: new Date('6/18/2022'),
    bags: 'n/a',
    tagNr: '233',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'BJ',
    bbLr: 'ID',
    bbOut: 'BR',
  },
  {
    luggageId: 'f8e46153-d8e1-46dd-ba37-bbaae5144499',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '61',
    name: 'Bentlee Mcasparan',
    arrivalTime: new Date('10/6/2022'),
    bags: 'n/a',
    tagNr: '9',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'CN',
    bbOut: 'CN',
  },
  {
    luggageId: 'dfdc0a22-0f17-4155-bdf0-8b76a967e3c3',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '04664',
    name: 'Wait Hutcheons',
    arrivalTime: new Date('9/9/2022'),
    bags: 'Major Banks',
    tagNr: '861',
    location: Location.HVG_HOVEDVAGTSGADE,
    bbDown: 'ID',
    bbLr: 'JP',
    bbOut: 'RU',
  },
];
