import { ILuggage, LuggageType } from '@hems/interfaces';

export const luggages: ILuggage[] = [
  {
    luggageId: '8f009c33-6fee-4abf-b176-ce9195420c46',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '86ø',
    name: 'Harvey Heimes',
    arrivalTime: new Date('8/28/2022'),
    bags: '7',
    tagNr: '2989',
    location: 'LR',
    bbDown: 'RU',
    bbLr: 'CD',
    bbOut: 'GB',
    description: 'Corvus brachyrhynchos',
    createdAt: new Date(Date.parse('2022-08-28 05:27:56.076')),
    completedAt: new Date(Date.parse('2022-08-28 05:27:56.076')),
  },
  {
    luggageId: 'e3a67552-1a6e-4a31-ac06-df626ab408f9',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '12',
    name: 'Adrian Stollwørck',
    arrivalTime: new Date('10/3/2022'),
    bags: '13',
    tagNr: '8',
    location: 'LR',
    bbDown: 'IL',
    bbLr: 'NO',
    bbOut: 'GT',
    description: 'Gyps bengalensis',
    createdAt: new Date(Date.parse('2022-08-28 14:27:56.076')),
    completedAt: new Date(Date.parse('2022-08-28 14:27:56.076')),
  },
  {
    luggageId: 'd7b146a4-0091-4d76-89ef-69a9fbb1e62a',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '66',
    name: 'Lyndsay Ettridge',
    arrivalTime: new Date('7/6/2022'),
    bags: '12',
    tagNr: '2802',
    location: 'LR',
    bbDown: 'VN',
    bbLr: 'PL',
    bbOut: 'Cæ',
    description: 'Ctenophorus ornatus',
    createdAt: new Date(Date.parse('2022-08-28 23:59:000')),
  },
  {
    luggageId: '4a76d3a6-1ddc-47da-b96a-7ea9d8187be8',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '5773',
    name: 'Rebekkah Schoffel',
    arrivalTime: new Date('1/19/2022'),
    bags: '4',
    tagNr: '537',
    location: 'LR',
    bbDown: 'AR',
    bbLr: 'ID',
    bbOut: 'TH',
    description: 'Nasua narica',
    createdAt: new Date(Date.parse('2022-08-27 23:59:000')),
  },
  {
    luggageId: 'c3ee63c5-30fa-4564-91a7-796210345bfa',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '76950',
    name: 'Melisande Burnard',
    arrivalTime: new Date('6/26/2022'),
    bags: '13',
    tagNr: '7',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'CY',
    bbOut: 'CN',
    description: 'Nyctea scandiaca',
    createdAt: new Date(Date.parse('2022-08-29 03:00:000')),
  },
  {
    luggageId: '8bfee9fb-63f0-42ae-9d6b-493005225411',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '68534',
    name: 'Ray Americi',
    arrivalTime: new Date('6/7/2022'),
    bags: '9',
    tagNr: '9420',
    location: 'LR',
    bbDown: 'Jø',
    bbLr: 'WS',
    bbOut: 'RU',
    description: 'Eubalaena australis',
    createdAt: new Date(Date.parse('2022-08-28 05:27:56.076')),
  },
  {
    luggageId: '6f53d1b3-2b1d-4b39-ae16-56cddf22c63b',
    luggageType: LuggageType.CHECKOUT,
    roomReady: false,
    room: '38',
    name: 'Kit Emm',
    arrivalTime: new Date('8/29/2022'),
    bags: '9',
    tagNr: '2122',
    location: 'LR',
    bbDown: 'PT',
    bbLr: 'ID',
    bbOut: 'FR',
    description: 'Cervus elaphus',
    createdAt: new Date(Date.parse('2022-08-28 23:59:000')),
  },
  {
    luggageId: '491ffd73-ffc6-405f-91b3-c7c9f8df5e94',
    luggageType: LuggageType.LONG_TERM,
    roomReady: false,
    room: '9',
    name: 'Hayward Quilkin',
    arrivalTime: new Date('10/20/2022'),
    bags: '11',
    tagNr: '6',
    location: 'LR',
    bbDown: 'UA',
    bbLr: 'BW',
    bbOut: 'CN',
    description: 'Hippotragus equinus',
    createdAt: new Date(Date.parse('2022-08-28 23:59:000')),
  },
  {
    luggageId: '4178fd4a-4968-4014-83c7-cc8e0ce48ac0',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '974',
    name: 'Othello Stillert',
    arrivalTime: new Date('8/16/2022'),
    bags: '12',
    tagNr: '6',
    location: 'LR',
    bbDown: 'NG',
    bbLr: 'PT',
    bbOut: 'US',
    description: 'Ploceus rubiginosus',
  },
  {
    luggageId: '23ce4dca-8c9d-4c70-a539-18eac67fef9c',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '27',
    name: 'Sabine Masarrat',
    arrivalTime: new Date('3/2/2022'),
    bags: '7',
    tagNr: '861',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'PH',
    bbOut: 'US',
    description: 'Plegadis ridgwayi',
  },
  {
    luggageId: 'd6f62e1e-431d-4b9a-8216-cb6b2e3c5d20',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '9688',
    name: 'Enrico Phillp',
    arrivalTime: new Date('9/9/2022'),
    bags: '2',
    tagNr: '367',
    location: 'LR',
    bbDown: 'RU',
    bbLr: 'CN',
    bbOut: 'YE',
    description: 'Alopex lagopus',
  },
  {
    luggageId: '353278b7-d4d0-4bd7-bd4c-ef75160ad38a',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '73',
    name: 'Delbert Shepeard',
    arrivalTime: new Date('4/28/2022'),
    bags: '15',
    tagNr: '7',
    location: 'LR',
    bbDown: 'PT',
    bbLr: 'CZ',
    bbOut: 'AR',
    description: 'Balearica pavonina',
  },
  {
    luggageId: 'e6e4d6e6-62b6-44b7-a546-469782b96f36',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '6699',
    name: 'Donetta Gurnell',
    arrivalTime: new Date('12/18/2021'),
    bags: '16',
    tagNr: '92',
    location: 'LR',
    bbDown: 'ID',
    bbLr: 'RU',
    bbOut: 'BR',
    description: 'Eira barbata',
  },
  {
    luggageId: 'cf7c022b-99bf-476f-99ac-f7676ca4dcfa',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '65',
    name: 'Tasia Stickings',
    arrivalTime: new Date('4/7/2022'),
    bags: '8',
    tagNr: '75',
    location: 'LR',
    bbDown: 'MG',
    bbLr: 'SE',
    bbOut: 'NE',
    description: 'Crax sp.',
  },
  {
    luggageId: '9e2c1aa7-9529-4f91-8bc3-0693c85f47dd',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '83',
    name: 'Regan Ravenhills',
    arrivalTime: new Date('3/11/2022'),
    bags: '3',
    tagNr: '1',
    location: 'LR',
    bbDown: 'SA',
    bbLr: 'CN',
    bbOut: 'SI',
    description: 'Limnocorax flavirostra',
  },
  {
    luggageId: 'f8bb49d7-6f73-4ffd-afea-a4b2abdfb0e9',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '65',
    name: 'Olia Rattry',
    arrivalTime: new Date('7/15/2022'),
    bags: '7',
    tagNr: '111',
    location: 'LR',
    bbDown: 'ID',
    bbLr: 'US',
    bbOut: 'CN',
    description: 'Ammospermophilus nelsoni',
  },
  {
    luggageId: '0b7911a8-2100-4a4c-b671-c42671486d08',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '55',
    name: 'Hunfredo Carrett',
    arrivalTime: new Date('12/28/2021'),
    bags: '14',
    tagNr: '034',
    location: 'LR',
    bbDown: 'BR',
    bbLr: 'ID',
    bbOut: 'ID',
    description: 'Axis axis',
  },
  {
    luggageId: 'e8db871d-e7db-4299-a26e-429ad31c2f92',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '0940',
    name: 'Renaud Geratt',
    arrivalTime: new Date('11/22/2021'),
    bags: '14',
    tagNr: '7',
    location: 'LR',
    bbDown: 'SE',
    bbLr: 'CN',
    bbOut: 'FM',
    description: 'Canis aureus',
  },
  {
    luggageId: 'cfdca80e-6525-4e0b-9e26-a0bf09dfc952',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '2667',
    name: 'Kay Whysall',
    arrivalTime: new Date('8/19/2022'),
    bags: '2',
    tagNr: '90',
    location: 'LR',
    bbDown: 'US',
    bbLr: 'CU',
    bbOut: 'NZ',
    description: 'Lepus townsendii',
  },
  {
    luggageId: '8042308c-7263-490b-b13f-1fcd5458d6b5',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '67352',
    name: 'Bobette Mc Corley',
    arrivalTime: new Date('10/27/2022'),
    bags: '11',
    tagNr: '30752',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'NP',
    bbOut: 'ID',
    description: 'Perameles nasuta',
  },
  {
    luggageId: '1f68b67e-87cd-470a-84cc-e0a9f307c2e3',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '5',
    name: 'Jenn Scaplehorn',
    arrivalTime: new Date('6/23/2022'),
    bags: '3',
    tagNr: '56853',
    location: 'LR',
    bbDown: 'CA',
    bbLr: 'CI',
    bbOut: 'ID',
    description: 'Callorhinus ursinus',
  },
  {
    luggageId: '68dfe3a1-f886-49ae-9efb-09760dc79f00',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '3587',
    name: 'Bendick Tomasutti',
    arrivalTime: new Date('10/19/2022'),
    bags: '15',
    tagNr: '16',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'US',
    bbOut: 'NE',
    description: 'Pterocles gutturalis',
  },
  {
    luggageId: '2e1182e6-8809-4b7e-95c6-016b86f3ee3b',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '3103',
    name: 'Luce Hynson',
    arrivalTime: new Date('4/4/2022'),
    bags: '5',
    tagNr: '85193',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'BJ',
    bbOut: 'RU',
    description: 'unavailable',
  },
  {
    luggageId: 'fa09f5f4-f7f5-4b1c-9c13-bc824ed6694d',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '39767',
    name: 'Edythe Mulqueen',
    arrivalTime: new Date('5/8/2022'),
    bags: '7',
    tagNr: '8448',
    location: 'LR',
    bbDown: 'ID',
    bbLr: 'PH',
    bbOut: 'CN',
    description: 'Morelia spilotes variegata',
  },
  {
    luggageId: 'f67912e2-59ad-42a9-9b00-842d563836f8',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '289',
    name: 'Sella Tebboth',
    arrivalTime: new Date('12/22/2021'),
    bags: '10',
    tagNr: '1',
    location: 'LR',
    bbDown: 'RU',
    bbLr: 'RU',
    bbOut: 'PT',
    description: 'Eumetopias jubatus',
  },
  {
    luggageId: 'aab3de37-1968-4d03-95ad-aebb6be5b3c5',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '26152',
    name: 'Anastasia Abeles',
    arrivalTime: new Date('4/3/2022'),
    bags: '10',
    tagNr: '47739',
    location: 'LR',
    bbDown: 'CY',
    bbLr: 'NO',
    bbOut: 'PT',
    description: 'Gymnorhina tibicen',
  },
  {
    luggageId: '7b1f2f59-8059-43a0-a5d2-c070bd83aaf9',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '85739',
    name: 'Gladys Thumim',
    arrivalTime: new Date('1/3/2022'),
    bags: '3',
    tagNr: '30799',
    location: 'LR',
    bbDown: 'PH',
    bbLr: 'NP',
    bbOut: 'CN',
    description: 'Milvago chimachima',
  },
  {
    luggageId: '07ea481f-4b31-4ee0-bc76-1412d40862ea',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '3472',
    name: 'Doug Timperley',
    arrivalTime: new Date('4/9/2022'),
    bags: '3',
    tagNr: '2391',
    location: 'LR',
    bbDown: 'RU',
    bbLr: 'PL',
    bbOut: 'RU',
    description: 'Colaptes campestroides',
  },
  {
    luggageId: 'b9f95593-c8f1-4e18-8da0-ba242e464dcd',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '13455',
    name: 'Emlen Eckels',
    arrivalTime: new Date('3/16/2022'),
    bags: '5',
    tagNr: '17',
    location: 'LR',
    bbDown: 'ID',
    bbLr: 'PL',
    bbOut: 'GB',
    description: 'Chelodina longicollis',
  },
  {
    luggageId: '1b1d9c17-afbe-4889-b8ba-b9ad1181ebaf',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '7',
    name: 'Bea Cheesworth',
    arrivalTime: new Date('5/26/2022'),
    bags: '15',
    tagNr: '7',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'CN',
    bbOut: 'MG',
    description: 'Choloepus hoffmani',
  },
  {
    luggageId: 'c07f9ba8-e30d-44a6-be42-2a62ba655148',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '4',
    name: 'Wally Lingwood',
    arrivalTime: new Date('3/13/2022'),
    bags: '8',
    tagNr: '918',
    location: 'LR',
    bbDown: 'MQ',
    bbLr: 'BY',
    bbOut: 'ID',
    description: 'Myrmecophaga tridactyla',
  },
  {
    luggageId: '69920949-d977-4f4b-af11-efda678fcfcc',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '9187',
    name: 'Cari Grumble',
    arrivalTime: new Date('4/18/2022'),
    bags: '5',
    tagNr: '90023',
    location: 'LR',
    bbDown: 'PT',
    bbLr: 'PT',
    bbOut: 'JP',
    description: 'Bos frontalis',
  },
  {
    luggageId: '0ff02040-3a66-42c4-9356-34fe4486fdb0',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '4',
    name: 'Willdon Parcell',
    arrivalTime: new Date('9/14/2022'),
    bags: '15',
    tagNr: '4',
    location: 'LR',
    bbDown: 'AT',
    bbLr: 'PE',
    bbOut: 'CN',
    description: 'Naja haje',
  },
  {
    luggageId: 'b27d7637-7ff2-4796-98ec-a038c20a8508',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '52',
    name: 'Berty Warwicker',
    arrivalTime: new Date('8/29/2022'),
    bags: '6',
    tagNr: '3646',
    location: 'LR',
    bbDown: 'US',
    bbLr: 'KZ',
    bbOut: 'CN',
    description: 'Streptopelia senegalensis',
  },
  {
    luggageId: '27438d80-bb63-495b-b3b9-a93f423bb982',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '738',
    name: 'Sammy Kikke',
    arrivalTime: new Date('8/15/2022'),
    bags: '10',
    tagNr: '4520',
    location: 'LR',
    bbDown: 'SE',
    bbLr: 'ID',
    bbOut: 'CZ',
    description: 'Toxostoma curvirostre',
  },
  {
    luggageId: '1e90f481-1027-4da8-8450-1de2702f988e',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '83',
    name: 'Perceval Sturror',
    arrivalTime: new Date('8/14/2022'),
    bags: '16',
    tagNr: '88',
    location: 'LR',
    bbDown: 'IR',
    bbLr: 'PL',
    bbOut: 'GR',
    description: 'Fulica cristata',
  },
  {
    luggageId: 'dfd769b4-de80-42be-ae32-bbd50a80cb00',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '56',
    name: 'Welch Gammon',
    arrivalTime: new Date('11/28/2021'),
    bags: '13',
    tagNr: '9',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'ID',
    bbOut: 'ID',
    description: 'Hippotragus equinus',
  },
  {
    luggageId: 'dc390b67-74ff-4c54-8ea6-f4ae5e303c04',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '28',
    name: 'Bryana Jurczak',
    arrivalTime: new Date('8/24/2022'),
    bags: '16',
    tagNr: '081',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'PL',
    bbOut: 'CZ',
    description: 'Pavo cristatus',
  },
  {
    luggageId: '5382ce5b-2a4d-4139-b200-a66e9fd7c8e0',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '6467',
    name: 'Ethelind Parrington',
    arrivalTime: new Date('10/26/2022'),
    bags: '8',
    tagNr: '1316',
    location: 'LR',
    bbDown: 'IS',
    bbLr: 'ID',
    bbOut: 'AR',
    description: 'Seiurus aurocapillus',
  },
  {
    luggageId: '3e8c1ef0-c7e9-4f47-9c1b-64f688a5877e',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '31880',
    name: 'Silvie Patrick',
    arrivalTime: new Date('4/28/2022'),
    bags: '4',
    tagNr: '0458',
    location: 'LR',
    bbDown: 'RU',
    bbLr: 'US',
    bbOut: 'DO',
    description: 'Butorides striatus',
  },
  {
    luggageId: '6ab1d430-3a4d-45d1-9558-afe81513b5ee',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '0804',
    name: 'Allys Dohms',
    arrivalTime: new Date('9/5/2022'),
    bags: '9',
    tagNr: '9',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'PK',
    bbOut: 'CY',
    description: 'Phoenicopterus ruber',
  },
  {
    luggageId: 'e12bb983-71c2-43c8-ab4b-0ca8b819cd4d',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '0436',
    name: 'Kaitlin Brashaw',
    arrivalTime: new Date('10/31/2022'),
    bags: '10',
    tagNr: '84770',
    location: 'LR',
    bbDown: 'DE',
    bbLr: 'CN',
    bbOut: 'CN',
    description: 'Phalacrocorax carbo',
  },
  {
    luggageId: 'ef103bfb-af66-4359-9e30-e053394c9873',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '537',
    name: 'Philip Ibotson',
    arrivalTime: new Date('7/22/2022'),
    bags: '13',
    tagNr: '95',
    location: 'LR',
    bbDown: 'CU',
    bbLr: 'GM',
    bbOut: 'CN',
    description: 'Canis aureus',
  },
  {
    luggageId: '27d83c5a-cf72-40e4-b364-8318dd119fd1',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '5',
    name: 'Stormi Notti',
    arrivalTime: new Date('7/31/2022'),
    bags: '14',
    tagNr: '4471',
    location: 'LR',
    bbDown: 'BR',
    bbLr: 'PH',
    bbOut: 'ID',
    description: 'Trichosurus vulpecula',
  },
  {
    luggageId: '13bdff61-13fb-430c-9e7f-dcdf72b19f04',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '268',
    name: 'Dela Lynnett',
    arrivalTime: new Date('3/10/2022'),
    bags: '16',
    tagNr: '0887',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'RS',
    bbOut: 'PT',
    description: 'Echimys chrysurus',
  },
  {
    luggageId: '5ff72255-6ef5-40f7-8a37-963f036cadda',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '07',
    name: 'Kathryne Eliasson',
    arrivalTime: new Date('1/29/2022'),
    bags: '6',
    tagNr: '05',
    location: 'LR',
    bbDown: 'LI',
    bbLr: 'RS',
    bbOut: 'FI',
    description: 'Herpestes javanicus',
  },
  {
    luggageId: '30c6f842-5ea7-4e30-b3aa-c371f2068278',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '94',
    name: 'Sonja Probert',
    arrivalTime: new Date('3/20/2022'),
    bags: '13',
    tagNr: '10715',
    location: 'LR',
    bbDown: 'PH',
    bbLr: 'ID',
    bbOut: 'FR',
    description: 'Damaliscus dorcas',
  },
  {
    luggageId: '037295d9-6f59-4cd2-bd28-d13db7beb41e',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '2',
    name: 'Nonna MacClancey',
    arrivalTime: new Date('7/30/2022'),
    bags: '13',
    tagNr: '52550',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'TN',
    bbOut: 'PH',
    description: 'Graspus graspus',
  },
  {
    luggageId: '02ce8548-1c68-4dca-96b6-bbd13aa6b5c2',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '55604',
    name: 'Chaddy Tarbet',
    arrivalTime: new Date('6/9/2022'),
    bags: '3',
    tagNr: '14312',
    location: 'LR',
    bbDown: 'CO',
    bbLr: 'FR',
    bbOut: 'KZ',
    description: 'Uraeginthus granatina',
  },
  {
    luggageId: 'bd7826ac-beb7-4410-b227-a7cfcd4cb9aa',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '31710',
    name: 'Rafaelia Harris',
    arrivalTime: new Date('5/31/2022'),
    bags: '7',
    tagNr: '5304',
    location: 'LR',
    bbDown: 'MX',
    bbLr: 'CN',
    bbOut: 'ID',
    description: 'Lasiodora parahybana',
  },
  {
    luggageId: '857319aa-a2b9-496d-b190-a7dcaf9b846a',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '766',
    name: 'Flory Goldsmith',
    arrivalTime: new Date('3/5/2022'),
    bags: '11',
    tagNr: '14',
    location: 'LR',
    bbDown: 'PH',
    bbLr: 'BR',
    bbOut: 'SE',
    description: 'Physignathus cocincinus',
  },
  {
    luggageId: 'c6b0a533-f5f4-47dc-b0b7-c9209a9abda5',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '34066',
    name: 'Norton Bickersteth',
    arrivalTime: new Date('8/4/2022'),
    bags: '13',
    tagNr: '76',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'CN',
    bbOut: 'ID',
    description: 'Priodontes maximus',
  },
  {
    luggageId: '61c6f3ff-4bdc-42f0-adff-5c622157b923',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '919',
    name: 'Donnie Trebbett',
    arrivalTime: new Date('9/4/2022'),
    bags: '9',
    tagNr: '0',
    location: 'LR',
    bbDown: 'UA',
    bbLr: 'BY',
    bbOut: 'ID',
    description: 'Dasyurus viverrinus',
  },
  {
    luggageId: '777c7f6c-6907-476a-b792-2ea43978c1ec',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '0',
    name: 'Kally Ketton',
    arrivalTime: new Date('1/16/2022'),
    bags: '12',
    tagNr: '1',
    location: 'LR',
    bbDown: 'US',
    bbLr: 'LV',
    bbOut: 'CN',
    description: 'Mycteria leucocephala',
  },
  {
    luggageId: 'a2e44242-988c-43d3-b88c-4cd0ad408934',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '13659',
    name: 'Audi Hook',
    arrivalTime: new Date('6/9/2022'),
    bags: '5',
    tagNr: '5',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'ID',
    bbOut: 'LT',
    description: 'Laniaurius atrococcineus',
  },
  {
    luggageId: '907cc4b3-3b31-44d8-9a7c-d13b0d30e9df',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '55',
    name: 'Spike Lettson',
    arrivalTime: new Date('6/29/2022'),
    bags: '3',
    tagNr: '42',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'YE',
    bbOut: 'PY',
    description: 'Ciconia episcopus',
  },
  {
    luggageId: '87958caf-c5e1-448f-aa0d-11c8898c0632',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '9488',
    name: 'Winonah Newlove',
    arrivalTime: new Date('12/5/2021'),
    bags: '12',
    tagNr: '2',
    location: 'LR',
    bbDown: 'DE',
    bbLr: 'SE',
    bbOut: 'PH',
    description: 'Phascogale calura',
  },
  {
    luggageId: '90052904-f5f9-4ca0-b767-61d9b97fb4ce',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '12166',
    name: 'Nanni Helleker',
    arrivalTime: new Date('7/12/2022'),
    bags: '12',
    tagNr: '97316',
    location: 'LR',
    bbDown: 'MN',
    bbLr: 'UA',
    bbOut: 'CO',
    description: 'Himantopus himantopus',
  },
  {
    luggageId: 'f5014b12-67dd-40af-80e2-8031862bdec4',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '13666',
    name: 'Shalom Rapaport',
    arrivalTime: new Date('5/9/2022'),
    bags: '6',
    tagNr: '8175',
    location: 'LR',
    bbDown: 'FR',
    bbLr: 'CN',
    bbOut: 'CN',
    description: 'Bassariscus astutus',
  },
  {
    luggageId: 'b8c974b6-c4e8-43ed-82d5-748a72bf8cd9',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '90142',
    name: 'Laird Crinidge',
    arrivalTime: new Date('9/18/2022'),
    bags: '4',
    tagNr: '8',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'CA',
    bbOut: 'CN',
    description: 'Geochelone elegans',
  },
  {
    luggageId: '98ca307e-af70-4d98-971b-2333c99820bb',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '9',
    name: 'Cheryl Shotton',
    arrivalTime: new Date('4/6/2022'),
    bags: '9',
    tagNr: '20383',
    location: 'LR',
    bbDown: 'ES',
    bbLr: 'RU',
    bbOut: 'FR',
    description: 'Gopherus agassizii',
  },
  {
    luggageId: '2221629f-2ffe-4a3b-a76f-44763cf32b1c',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '77765',
    name: 'Adara Wabb',
    arrivalTime: new Date('4/1/2022'),
    bags: '13',
    tagNr: '41658',
    location: 'LR',
    bbDown: 'PH',
    bbLr: 'ID',
    bbOut: 'ID',
    description: 'Panthera pardus',
  },
  {
    luggageId: '525cb19f-2c31-4d9c-af8c-cb0ff7fcfd38',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '9216',
    name: 'Ashby Reed',
    arrivalTime: new Date('5/9/2022'),
    bags: '16',
    tagNr: '32063',
    location: 'LR',
    bbDown: 'SE',
    bbLr: 'TH',
    bbOut: 'US',
    description: 'Cervus duvauceli',
  },
  {
    luggageId: 'fc94e63f-42c1-4a73-a2cb-39ae949a8ac1',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '3',
    name: 'Gerome Tunkin',
    arrivalTime: new Date('3/9/2022'),
    bags: '2',
    tagNr: '05032',
    location: 'LR',
    bbDown: 'JP',
    bbLr: 'PL',
    bbOut: 'CL',
    description: 'Cordylus giganteus',
  },
  {
    luggageId: '7e35c1f0-8570-4705-9cfa-9b4eaf395356',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '47',
    name: 'Rubin Bertomier',
    arrivalTime: new Date('9/27/2022'),
    bags: '3',
    tagNr: '20198',
    location: 'LR',
    bbDown: 'BR',
    bbLr: 'NG',
    bbOut: 'SY',
    description: 'Mirounga angustirostris',
  },
  {
    luggageId: '345c3087-0661-4881-80f2-64d73fc9b468',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '12',
    name: 'Nell Maccrie',
    arrivalTime: new Date('7/30/2022'),
    bags: '1',
    tagNr: '69822',
    location: 'LR',
    bbDown: 'PE',
    bbLr: 'MG',
    bbOut: 'CA',
    description: 'Epicrates cenchria maurus',
  },
  {
    luggageId: 'e405b5a1-24dd-4a99-a025-8aee3aefef6d',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '56043',
    name: 'Masha Rack',
    arrivalTime: new Date('7/29/2022'),
    bags: '4',
    tagNr: '6066',
    location: 'LR',
    bbDown: 'PH',
    bbLr: 'CN',
    bbOut: 'PT',
    description: 'Limnocorax flavirostra',
  },
  {
    luggageId: 'e4167795-04bf-4f58-b8ee-189d897f6fb6',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '6186',
    name: 'Arie Kail',
    arrivalTime: new Date('6/30/2022'),
    bags: '16',
    tagNr: '257',
    location: 'LR',
    bbDown: 'ID',
    bbLr: 'DO',
    bbOut: 'ID',
    description: 'Odocoileus hemionus',
  },
  {
    luggageId: 'd2570c90-8d87-49e2-a0df-d82f516b28c9',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '69',
    name: 'Brian Biasio',
    arrivalTime: new Date('5/10/2022'),
    bags: '3',
    tagNr: '1603',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'CN',
    bbOut: 'PH',
    description: 'Sciurus niger',
  },
  {
    luggageId: '2bb9c208-a273-4179-89e7-f8aff7495d28',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '9091',
    name: 'Ingram Crawshaw',
    arrivalTime: new Date('5/2/2022'),
    bags: '9',
    tagNr: '52',
    location: 'LR',
    bbDown: 'ID',
    bbLr: 'BR',
    bbOut: 'CA',
    description: 'Anhinga rufa',
  },
  {
    luggageId: '5f851e17-e2d6-44da-9dcb-4b156ed577f6',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '5',
    name: 'Lia Goldes',
    arrivalTime: new Date('10/19/2022'),
    bags: '11',
    tagNr: '32',
    location: 'LR',
    bbDown: 'ID',
    bbLr: 'RU',
    bbOut: 'SE',
    description: 'Tamiasciurus hudsonicus',
  },
  {
    luggageId: 'bf1714f0-1978-4e00-b9fe-a5bc56cf3548',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '6',
    name: 'Andeee Endrici',
    arrivalTime: new Date('5/29/2022'),
    bags: '5',
    tagNr: '6',
    location: 'LR',
    bbDown: 'FR',
    bbLr: 'SY',
    bbOut: 'BY',
    description: 'Tachybaptus ruficollis',
  },
  {
    luggageId: 'fc524234-8505-4567-bc5b-99da4180a2fa',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '0',
    name: 'Doralin Jeandel',
    arrivalTime: new Date('10/27/2022'),
    bags: '3',
    tagNr: '3423',
    location: 'LR',
    bbDown: 'PL',
    bbLr: 'ID',
    bbOut: 'PT',
    description: 'Suricata suricatta',
  },
  {
    luggageId: '35d8c66e-52e9-486c-bf16-6bacf1e245d7',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '75',
    name: 'Koressa Roze',
    arrivalTime: new Date('3/31/2022'),
    bags: '12',
    tagNr: '75',
    location: 'LR',
    bbDown: 'PK',
    bbLr: 'CZ',
    bbOut: 'VE',
    description: 'Ephippiorhynchus mycteria',
  },
  {
    luggageId: '8fefae40-2daf-4ed6-882c-e222cf016c70',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '04697',
    name: 'Friederike Hammerberg',
    arrivalTime: new Date('9/4/2022'),
    bags: '14',
    tagNr: '3',
    location: 'LR',
    bbDown: 'JM',
    bbLr: 'AL',
    bbOut: 'PH',
    description: 'Varanus sp.',
  },
  {
    luggageId: '2c1a46c9-9501-426d-a5f2-f69da8957f47',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '57',
    name: 'Linnet Okell',
    arrivalTime: new Date('2/19/2022'),
    bags: '1',
    tagNr: '6',
    location: 'LR',
    bbDown: 'ID',
    bbLr: 'PH',
    bbOut: 'AF',
    description: 'Phalacrocorax albiventer',
  },
  {
    luggageId: '3ee53503-b0bb-435f-b660-d9528f722f49',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '82984',
    name: 'Christophe Macknish',
    arrivalTime: new Date('10/22/2022'),
    bags: '1',
    tagNr: '07835',
    location: 'LR',
    bbDown: 'SE',
    bbLr: 'PH',
    bbOut: 'MD',
    description: 'Geochelone elephantopus',
  },
  {
    luggageId: 'eab84610-2881-40fb-ae5a-1eeac896a849',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '5711',
    name: 'Robby De Winton',
    arrivalTime: new Date('11/2/2022'),
    bags: '16',
    tagNr: '4',
    location: 'LR',
    bbDown: 'AR',
    bbLr: 'PH',
    bbOut: 'IE',
    description: 'Rhea americana',
  },
  {
    luggageId: 'c0e9d2f0-dfee-4e5a-9242-cac63242d781',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '1125',
    name: 'Row Westover',
    arrivalTime: new Date('4/1/2022'),
    bags: '8',
    tagNr: '694',
    location: 'LR',
    bbDown: 'HR',
    bbLr: 'SE',
    bbOut: 'NG',
    description: 'Redunca redunca',
  },
  {
    luggageId: '9facc3ba-7871-40d0-b37c-5d2fcb4a0194',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '4173',
    name: 'Hanna Firminger',
    arrivalTime: new Date('12/4/2021'),
    bags: '16',
    tagNr: '622',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'BA',
    bbOut: 'HU',
    description: 'Eutamias minimus',
  },
  {
    luggageId: '12035410-1fe8-44f6-939c-ebb57e3dfff8',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '3',
    name: 'Gracie Edgerly',
    arrivalTime: new Date('1/18/2022'),
    bags: '1',
    tagNr: '344',
    location: 'LR',
    bbDown: 'TH',
    bbLr: 'RU',
    bbOut: 'CA',
    description: 'Felis silvestris lybica',
  },
  {
    luggageId: 'c3aec83d-6b30-4182-81b5-0e3012be5239',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '8752',
    name: 'Papageno Poulden',
    arrivalTime: new Date('1/9/2022'),
    bags: '7',
    tagNr: '86',
    location: 'LR',
    bbDown: 'KE',
    bbLr: 'US',
    bbOut: 'FR',
    description: 'Columba livia',
  },
  {
    luggageId: '70cad892-de1b-4990-9b6d-c46c8cadd60f',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '24',
    name: 'Debee Hintze',
    arrivalTime: new Date('6/26/2022'),
    bags: '7',
    tagNr: '5797',
    location: 'LR',
    bbDown: 'CZ',
    bbLr: 'LU',
    bbOut: 'AR',
    description: 'Panthera leo',
  },
  {
    luggageId: 'bb1e410b-4cfb-4070-8352-ba4244b99a93',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '34598',
    name: 'Janette Willacot',
    arrivalTime: new Date('2/9/2022'),
    bags: '4',
    tagNr: '7',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'CN',
    bbOut: 'PT',
    description: 'Dasypus septemcincus',
  },
  {
    luggageId: '9bb5ce5c-b029-4117-8482-21f939a4281a',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '17985',
    name: 'Addy Masarrat',
    arrivalTime: new Date('2/3/2022'),
    bags: '16',
    tagNr: '815',
    location: 'LR',
    bbDown: 'MG',
    bbLr: 'GW',
    bbOut: 'CN',
    description: 'Papilio canadensis',
  },
  {
    luggageId: '6afaa613-b5d6-4f9a-b69a-429ef5d72cef',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '21438',
    name: 'Jessalin Curryer',
    arrivalTime: new Date('12/21/2021'),
    bags: '16',
    tagNr: '193',
    location: 'LR',
    bbDown: 'FR',
    bbLr: 'YE',
    bbOut: 'CN',
    description: 'Uraeginthus granatina',
  },
  {
    luggageId: '1856ddc3-33ed-4156-91d1-7d6bda2ab915',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '89',
    name: 'Donavon Walne',
    arrivalTime: new Date('1/27/2022'),
    bags: '3',
    tagNr: '0',
    location: 'LR',
    bbDown: 'GR',
    bbLr: 'KZ',
    bbOut: 'BR',
    description: 'Pan troglodytes',
  },
  {
    luggageId: 'b9d60c5b-6653-45c7-9c13-612055b82d65',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '1',
    name: 'Veriee Bremmer',
    arrivalTime: new Date('8/4/2022'),
    bags: '10',
    tagNr: '93029',
    location: 'LR',
    bbDown: 'BD',
    bbLr: 'PT',
    bbOut: 'CO',
    description: 'Bubalornis niger',
  },
  {
    luggageId: '2b351532-6f1a-48f3-8e76-7c5884347a48',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '6',
    name: 'Diann Marousek',
    arrivalTime: new Date('10/29/2022'),
    bags: '1',
    tagNr: '363',
    location: 'LR',
    bbDown: 'MA',
    bbLr: 'ID',
    bbOut: 'PH',
    description: 'Lama pacos',
  },
  {
    luggageId: '64f21169-53b0-459d-a31f-bed3242b1a0e',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '8',
    name: 'Byron Stannett',
    arrivalTime: new Date('2/14/2022'),
    bags: '12',
    tagNr: '48838',
    location: 'LR',
    bbDown: 'PE',
    bbLr: 'PH',
    bbOut: 'CN',
    description: 'Perameles nasuta',
  },
  {
    luggageId: 'dc859a01-7db7-42a5-b546-9809d13fc6e6',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '83',
    name: 'Izzy Cow',
    arrivalTime: new Date('10/23/2022'),
    bags: '8',
    tagNr: '9',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'GR',
    bbOut: 'SV',
    description: 'Eumetopias jubatus',
  },
  {
    luggageId: '6018d952-2b1b-4b4f-9bcc-32d95fcb7e68',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '65',
    name: 'Haven Erdes',
    arrivalTime: new Date('2/22/2022'),
    bags: '16',
    tagNr: '6575',
    location: 'LR',
    bbDown: 'PH',
    bbLr: 'CN',
    bbOut: 'BR',
    description: 'Macropus robustus',
  },
  {
    luggageId: '174a9ede-64a2-4606-a34f-bbc08a10ab37',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '91',
    name: 'Vanya Perch',
    arrivalTime: new Date('1/9/2022'),
    bags: '7',
    tagNr: '054',
    location: 'LR',
    bbDown: 'GQ',
    bbLr: 'FI',
    bbOut: 'MY',
    description: 'Ursus arctos',
  },
  {
    luggageId: '8d8c0032-4291-46ab-b337-df3f250682ef',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '908',
    name: 'Napoleon Trowle',
    arrivalTime: new Date('6/22/2022'),
    bags: '4',
    tagNr: '23',
    location: 'LR',
    bbDown: 'CN',
    bbLr: 'ID',
    bbOut: 'AR',
    description: 'Zenaida galapagoensis',
  },
  {
    luggageId: 'e0f5c857-7914-4dfe-8569-930237a72e28',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '49482',
    name: 'Flor Jezard',
    arrivalTime: new Date('10/1/2022'),
    bags: '10',
    tagNr: '540',
    location: 'LR',
    bbDown: 'CM',
    bbLr: 'GR',
    bbOut: 'LT',
    description: 'Pterocles gutturalis',
  },
  {
    luggageId: '09a8f6aa-7aa4-4754-8043-8e09e39de41f',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '92',
    name: 'Leena Pepis',
    arrivalTime: new Date('4/25/2022'),
    bags: '4',
    tagNr: '321',
    location: 'LR',
    bbDown: 'UY',
    bbLr: 'SE',
    bbOut: 'PH',
    description: 'Francolinus swainsonii',
  },
  {
    luggageId: '363f9187-ae21-444a-9fad-16f7a7a88674',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '8713',
    name: 'Buckie Romke',
    arrivalTime: new Date('8/12/2022'),
    bags: '14',
    tagNr: '3',
    location: 'LR',
    bbDown: 'AR',
    bbLr: 'PH',
    bbOut: 'MX',
    description: 'Lybius torquatus',
  },
  {
    luggageId: 'facb9141-68f3-40d5-b6ed-ac8d8a35bef3',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '670',
    name: 'Jan Iacobacci',
    arrivalTime: new Date('10/17/2022'),
    bags: '13',
    tagNr: '897',
    location: 'LR',
    bbDown: 'TJ',
    bbLr: 'ID',
    bbOut: 'LT',
    description: 'Ara ararauna',
  },
  {
    luggageId: 'ae7d879c-fe1a-4ec6-b2a2-d5e602eca483',
    luggageType: LuggageType.CHECKIN,
    roomReady: false,
    room: '32532',
    name: 'Raimondo Pietrzyk',
    arrivalTime: new Date('6/3/2022'),
    bags: '13',
    tagNr: '72405',
    location: 'LR',
    bbDown: 'PL',
    bbLr: 'CO',
    bbOut: 'RU',
    description: 'Phalaropus lobatus',
  },
  {
    luggageId: '38b3c8d2-ca2a-423c-b11b-9166324cf44a',
    luggageType: LuggageType.CHECKIN,
    roomReady: true,
    room: '3567',
    name: 'Cathleen Boate',
    arrivalTime: new Date('5/24/2022'),
    bags: '11',
    tagNr: '0',
    location: 'LR',
    bbDown: 'SI',
    bbLr: 'RU',
    bbOut: 'CU',
    description: 'Vanellus sp.',
  },
];
